spring:
  main:
    banner-mode: off
server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework: INFO
    dev.christopherbell.www: DEBUG
---
spring:
  profiles:
    default: local

